GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDk3MTQxNDZ9.YPK93-tbDex0LxjNeGO0PQwCQJMt4kH2OWWTEPFGdJ4

###

POST http://localhost:3000/login

Content-Type: application/json
{
    "username":"Cookie"
}